### ISSUE TITLE
Feature Checklist

### ISSUE THREAD

**Issue by ROODAY** [SquadUp/SquadUp#1]
- [ ] Create/Join Squads
- [ ] Squads can either have a leader to set events or let anyone set events (Squad Creator decides)
- [ ] Events have a name, time, place, and who's going
- [ ] GPS integration to get to destination
- [ ] Toggle-able "bruh" notification mode. This would make the notification noise be "bruh" and it would get louder the farther away you were from the event location. Notifications only end when you fist bump phones with the event creator (NFC)
- [ ] Who owes who money and how much (have input box for non-money payback)

**Comment by ROODAY** [comment]
http://android-developers.blogspot.com/2013/01/verifying-back-end-calls-from-android.html
https://developers.google.com/identity/sign-in/web/backend-auth
https://developers.google.com/identity/protocols/CrossClientAuth
